name: Lint Test and Deploy 
on: [push, workflow_dispatch]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get Codes of Node application
      uses: actions/checkout@v3
    - name: Install Node js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Dependencies
      run: npm ci
    - name: Run Test
    - name: Lint the Package
      run: npm run lint -- --fix
      run: npm test
    - name: Build Deploy
      run: echo "Deploying .."

  
